language: python
python:
    - "3.7-dev"
    - "3.8"
    - "3.9"
    - "3.10"

# install deps
install:
    - pip install flake8 isort coverage coveralls
    - pip install -r requirements.txt

before_script:
   - flake8 --show-source .
   - isort -rc .

# run tests
script: coverage run --source=pyfirmata tests.py

after_success:
    - coveralls
